Traceback (most recent call last):
  File "execute_fail_undeclared.py", line 1, in <module>
    print(a)
NameError: name 'a' is not defined
